# Generated by Django 4.2.3 on 2023-07-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uavs", "0002_alter_uavmanifacturer_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="uavmanifacturer",
            managers=[],
        ),
        migrations.AlterField(
            model_name="uavmanifacturertranslation",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="uavmanifacturertranslation",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="uavtranslation",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
