# Generated by Django 4.2.3 on 2023-07-14 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import parler.fields
import parler.models


class Migration(migrations.Migration):
    dependencies = [
        ("uavs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="uavmanifacturer",
            managers=[
                ("_tree_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="uav",
            name="description",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="name",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="uavcategory",
            name="name",
        ),
        migrations.RemoveField(
            model_name="uavcategory",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="uavmanifacturer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="uavmanifacturer",
            name="slug",
        ),
        migrations.CreateModel(
            name="UAVTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="uavs.uav",
                    ),
                ),
            ],
            options={
                "verbose_name": "uav Translation",
                "db_table": "uavs_uav_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="UAVManifacturerTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="uavs.uavmanifacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "uav manifacturer Translation",
                "db_table": "uavs_uavmanifacturer_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="UAVCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="uavs.uavcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "uav category Translation",
                "db_table": "uavs_uavcategory_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
